In [ ]:
import gdown

gdown.download(
    'https://www.data4library.kr/comn/fileDownload?cn=390685',
    '남산도서관 장서 대출목록 (2026년 09월).csv',
    quiet=False
)

In [ ]:
import chardet
with open('남산도서관 장서 대출목록 (2026년 09월).csv', mode = 'rb') as f:
  d = f.readline()
print(chardet.detect(d))

{'encoding': 'UTF-8-SIG', 'confidence': 1.0, 'language': ''}

파이썬의 with 문은 파일 같은 자원을 사용한 뒤, 필요한 정리 작업을 자동으로 처리하게 하는 문법입니다.

파일을 다룰 때는 사용이 끝나면 자동으로 파일을 닫아 줍니다.

In [ ]:
with open('남산도서관 장서 대출목록 (2026년 09월).csv') as f:
  print(f.readline())
  print(f.readline())
  print(f.readline())

﻿번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자,

"1","서울 사람들의 출산과 육아 ","서울역사편찬원","","2026","9791160712391","","9","28","911.6","1","0","2026-09-29",

"2","서울의 무속","서울역사편찬원","","2026","9791160712445","","9","29","911.6","1","0","2026-09-29",

In [ ]:
import pandas as pd
df = pd.read_csv('남산도서관 장서 대출목록 (2026년 09월).csv', encoding='UTF-8-SIG')

/tmp/ipykernel_1251/1944375784.py:2: DtypeWarning: Columns (5,7,9) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('남산도서관 장서 대출목록 (2026년 09월).csv', encoding='UTF-8-SIG')

# 출력된 경고의 의미

출력된 경고:
/tmp/ipykernel_1251/1944375784.py:2: DtypeWarning: Columns (5,7,9) have mixed types. Specify dtype option on import or set low_memory=False.

**파일은 읽혔지만, 일부 열의 값을 숫자로 처리할지 문자로 처리할지 일관되게 판단하기 어려웠다는 경고입니다.** 실행을 중단시키는 오류는 아니며, 지정하신 `UTF-8-SIG` 인코딩 때문에 발생한 것도 아닙니다.

판다스는 CSV를 읽으면서 각 열의 **자료형**을 자동으로 판단합니다. 큰 파일을 여러 부분으로 나누어 읽다가 같은 열을 어떤 부분에서는 숫자로, 다른 부분에서는 문자로 판단하면 이런 `DtypeWarning`이 발생할 수 있습니다. [판다스 공식 설명](https://pandas.pydata.org/docs/reference/api/pandas.errors.DtypeWarning.html)

`Columns (5,7,9)`는 **0부터 센 열 번호**입니다. 앞서 확인한 파일의 열 순서에 따르면 다음 항목입니다.

| 경고의 번호 | 실제 위치 | 열 이름 |
|---|---|---|
| 5 | 6번째 열 | ISBN |
| 7 | 8번째 열 | 부가기호 |
| 9 | 10번째 열 | 주제분류번호 |

정확히 어떤 값 때문에 발생했는지는 이 경고만으로는 알 수 없습니다. 다만 이 항목들은 **계산할 수량보다는 식별번호·분류코드**이므로, 처음부터 문자열로 읽도록 지정하는 편이 좋습니다.

```python
import pandas as pd

df = pd.read_csv(
    '남산도서관 장서 대출목록 (2026년 09월).csv',
    encoding='utf-8-sig',
    dtype={
        'ISBN': 'string',
        '부가기호': 'string',
        '주제분류번호': 'string'
    },
    low_memory=False
)

df.head()
```

여기서 **`dtype`은 지정한 열을 어떤 자료형으로 읽을지 정하는 옵션**입니다. `'string'`으로 지정하면 숫자처럼 생긴 코드도 문자로 읽어 앞자리의 `0` 등을 보존할 수 있습니다.

**`low_memory=False`**는 나누어 읽는 과정에서 자료형을 서로 다르게 추정하는 문제를 피하도록 하는 옵션입니다. 이것만 추가해도 해당 경고를 피할 수 있지만, 원자료의 잘못된 값을 고쳐 주는 기능은 아닙니다. [읽기 옵션 안내](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html)

마지막으로 `/tmp/ipykernel_…/….py:2`는 **코랩 내부에서 실행한 코드의 두 번째 줄에서 경고가 발생했다**는 위치 안내입니다.

In [ ]:
df = pd.read_csv('남산도서관 장서 대출목록 (2026년 09월).csv', encoding='UTF-8-SIG',
                 low_memory=False)

In [ ]:
df.head()

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자,Unnamed: 13
0,1,서울 사람들의 출산과 육아,서울역사편찬원,NaN,2026,9791160712391,NaN,9,28,911.6,1,0,2026-09-29,NaN
1,2,서울의 무속,서울역사편찬원,NaN,2026,9791160712445,NaN,9,29,911.6,1,0,2026-09-29,NaN
2,3,한민족 독립운동 노래모이,김보희 편저,NaN,2025,9791190965613,NaN,9,2,670.9,1,0,2026-09-29,NaN
3,4,한민족 독립운동 노래모이,김보희 편저,NaN,2025,9791190965606,NaN,9,1,670.9,1,0,2026-09-29,NaN
4,5,(譯註) 退溪全書,李滉 저; 퇴계학연구소 편,퇴계학연구원,2026,9791199324664,NaN,9,12,151.53,1,0,2026-09-29,NaN

# csv 파일 첫 행의 열이 '변인들 이름'이 아닌 경우에 대처법

CSV 파일의 첫 행이 열 이름이 아니라면 read_csv() 함수를 호출할 때 header 매개변수를 None 으로 지정해서 데이터 첫 행에 열 이름이 없다는 것을 알리고, names 매개변수에 열 이름 리스트를 따로 전달해 줍니다.

이때 names 매개변수에 전달하는 열 이름에 중복된 이름이 있어서는 안 됩니다.

In [ ]:
df.to_csv('ns_202609.csv')

In [ ]:
with open('ns_202609.csv') as f:
  for i in range(3):
    print(f.readline(), end='')

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자,Unnamed: 13
0,1,서울 사람들의 출산과 육아 ,서울역사편찬원,,2026,9791160712391,,9,28,911.6,1,0,2026-09-29,
1,2,서울의 무속,서울역사편찬원,,2026,9791160712445,,9,29,911.6,1,0,2026-09-29,

In [ ]:
ns_df = pd.read_csv('ns_202609.csv', low_memory=False)
ns_df.head()

,Unnamed: 0,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자,Unnamed: 13
0,0,1,서울 사람들의 출산과 육아,서울역사편찬원,NaN,2026,9791160712391,NaN,9,28,911.6,1,0,2026-09-29,NaN
1,1,2,서울의 무속,서울역사편찬원,NaN,2026,9791160712445,NaN,9,29,911.6,1,0,2026-09-29,NaN
2,2,3,한민족 독립운동 노래모이,김보희 편저,NaN,2025,9791190965613,NaN,9,2,670.9,1,0,2026-09-29,NaN
3,3,4,한민족 독립운동 노래모이,김보희 편저,NaN,2025,9791190965606,NaN,9,1,670.9,1,0,2026-09-29,NaN
4,4,5,(譯註) 退溪全書,李滉 저; 퇴계학연구소 편,퇴계학연구원,2026,9791199324664,NaN,9,12,151.53,1,0,2026-09-29,NaN

In [ ]:
ns_df=pd.read_csv('ns_202609.csv', index_col=0, low_memory=False)
ns_df.head()

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자,Unnamed: 13
0,1,서울 사람들의 출산과 육아,서울역사편찬원,NaN,2026,9791160712391,NaN,9,28,911.6,1,0,2026-09-29,NaN
1,2,서울의 무속,서울역사편찬원,NaN,2026,9791160712445,NaN,9,29,911.6,1,0,2026-09-29,NaN
2,3,한민족 독립운동 노래모이,김보희 편저,NaN,2025,9791190965613,NaN,9,2,670.9,1,0,2026-09-29,NaN
3,4,한민족 독립운동 노래모이,김보희 편저,NaN,2025,9791190965606,NaN,9,1,670.9,1,0,2026-09-29,NaN
4,5,(譯註) 退溪全書,李滉 저; 퇴계학연구소 편,퇴계학연구원,2026,9791199324664,NaN,9,12,151.53,1,0,2026-09-29,NaN

In [ ]:
ns_df.to_excel('ns_202609.xlsx', index=False)