# 파이썬에서 JSON 다루기

In [ ]:
d = {"name": "혼자 공부하는 데이터 분석"}
print(d['name'])

혼자 공부하는 데이터 분석

In [ ]:
import json

In [ ]:
d_str = json.dumps(d, ensure_ascii=False)
print(d_str)

{"name": "혼자 공부하는 데이터 분석"}

`dump`는 프로그래밍에서는 **데이터를 내보내거나 기록한다**는 의미로 사용합니다.

- **`json.dump()`**: 데이터를 JSON 형식으로 바꾸어 **파일 등에 기록**합니다.
- **`json.dumps()`**: 데이터를 JSON 형식의 **문자열로 만들어 반환**합니다.

`dumps`는 `dump` + `s`(string, 문자열)로 이해하시면 됩니다.

In [ ]:
print(type(d_str))
print(type(d))

<class 'str'>
<class 'dict'>

In [ ]:
d2=json.loads(d_str)
print(d2['name'])

혼자 공부하는 데이터 분석

`loads`는 `load` + `s`(string, 문자열)로 이해하면 됩니다.

- **`json.loads()`**: JSON **문자열**을 읽어 파이썬 데이터로 바꿉니다.
- **`json.load()`**: **파일**에서 JSON을 읽어 파이썬 데이터로 바꿉니다.

따라서 다음 코드는

```python
d3 = json.loads(json_text)
```

"`json_text`에 담긴 JSON 문자열을 파이썬 데이터로 변환해서 `d3`에 저장한다"는 뜻입니다.

In [ ]:
d3 = json.loads('{"name": "혼자 공부하는 데이터 분석", "author": "박해선", "year": 2022 }')

print(d3['name'])
print(d3['author'])
print(d3['year'])

혼자 공부하는 데이터 분석
박해선
2022

In [ ]:
d3 = json.loads('{"name": "혼자 공부하는 데이터 분석", "author": ["박해선", "김영빈"], "year": 2022}')
print(d3['author'][1])

김영빈

In [ ]:
d4_str = """
[
  {"name": "혼공데이터분석", "author": "박해선", "year": 2022},
  {"name": "혼공머신+딥러닝", "author": "박해선", "year": 2020}
]
"""
d4 = json.loads(d4_str)
print(d4[0]['name'])

혼공데이터분석

In [ ]:
from io import StringIO
import pandas as pd
pd.read_json(StringIO(d4_str))

       name author  year
0   혼공데이터분석    박해선  2022
1  혼공머신+딥러닝    박해선  2020

이 코드는 **`d4_str`에 들어 있는 JSON 문자열을 판다스의 데이터프레임, 즉 표로 읽어 오는 코드**입니다.

각 줄의 역할을 살펴보겠습니다.

**① `from io import StringIO`**

파이썬의 `io` 모듈에서 `StringIO`를 가져옵니다. **`StringIO`는 메모리에 있는 문자열을 파일처럼 읽을 수 있도록 해 주는 기능**입니다. `IO`는 입력·출력인 *Input/Output*을 뜻합니다. [파이썬 공식 설명](https://docs.python.org/3/library/io.html#io.StringIO)

**② `import pandas as pd`**

데이터 분석 도구인 `pandas`를 가져와서, 코드에서는 짧게 **`pd`라는 이름으로 사용하겠다**는 뜻입니다.

**③ `pd.read_json(StringIO(d4_str))`**

괄호 안쪽부터 실행됩니다.

1. **`StringIO(d4_str)`**: JSON 문자열을 파일처럼 읽을 수 있는 형태로 준비합니다.
2. **`pd.read_json(...)`**: 그 내용을 JSON으로 해석하여 데이터프레임으로 만듭니다. [판다스 공식 설명](https://pandas.pydata.org/docs/reference/api/pandas.read_json.html)

흐름으로 표현하면 다음과 같습니다.

```text
JSON 문자열 → 파일처럼 읽을 수 있는 형태 → 데이터프레임(표)
 d4_str              StringIO              pd.read_json
```

코랩에서는 마지막 줄의 결과가 표로 표시됩니다. 이 표를 이후에도 사용하시려면 변수에 저장하시면 됩니다.

```python
df = pd.read_json(StringIO(d4_str))
```

앞서 배운 **`json.loads()`가 JSON 문자열을 딕셔너리나 리스트 등으로 바꾼다면**, 여기의 **`pd.read_json()`은 데이터 분석에 사용할 표로 읽어 옵니다.**

In [ ]:
pd.DataFrame(d4)

       name author  year
0   혼공데이터분석    박해선  2022
1  혼공머신+딥러닝    박해선  2020

# 파이썬에서 XML 다루기

In [ ]:
x_str="""
<book>
  <name>혼공데이터분석</name>
  <author>박해선</author>
  <year>2022</year>
</book>
"""

In [ ]:
import xml.etree.ElementTree as et
book = et.fromstring(x_str)

# json 패키지는JSON 문자열을 파이썬 객체로 변환하지만,
# fromstring() 함수가 반환하는 객체는 단순한 파이썬 객체가 아니라
# ElementTree 모듈 아래에 정의된 Element 클래스의 객체입니다.
# type()함수로 fromstring() 함수가 어떤 객체를 반환하는지 book 변수의 타입을 확인해 보면 다음과 같습니다.

print(type(book))

# 또한 book 객체는 x_str에서 가장 먼저 등장하는 부모 엘리먼트인 에 해당합니다.
# book 객체의 tag 속성을 출력하면 엘리먼트 이름을 쉽게 확인할 수 있습니다.

print(book.tag)

<class 'xml.etree.ElementTree.Element'>
book

In [ ]:
book_childs = list(book)
print(book_childs)

[<Element 'name' at 0x7f55d03ac9f0>, <Element 'author' at 0x7f55d03aca90>, <Element 'year' at 0x7f55d03acb30>]

In [ ]:
name, author, year = book_childs
print(name.text)
print(author.text)
print(year.text)

혼공데이터분석
박해선
2022

In [ ]:
name = book.findtext('name')
author = book.findtext('author')
year = book.findtext('year')
print(name)
print(author)
print(year)

혼공데이터분석
박해선
2022

In [ ]:
x2_str = """
<books>
  <book>
    <name>혼공데이터분석</name>
    <author>박해선</author>
    <year>2022</year>
  </book>
  <book>
    <name>혼공머신+딥러닝</name>
    <author>박해선</author>
    <year>2020</year>
  </book>
</books>
"""

In [ ]:
books = et.fromstring(x2_str)
print(books.tag)

books

In [ ]:
for book in books.findall('book'):
  name = book.findtext('name')
  author = book.findtext('author')
  year = book.findtext('year')
  print(name)
  print(author)
  print(year)
  print()

혼공데이터분석
박해선
2022

혼공머신+딥러닝
박해선
2020

JSON의 경우 API에서 전달한 텍스트를 json.loads() 함수를 사용해 파이썬 객체로 바꾸어 내용을 추출했다면,

XML은 xml.etree.ElementTree 모듈에 있는 fromstring() 함수를 사용하여 부모 (루트) 엘리먼트를 얻고, findall() 메서드로 자식 엘리먼트에 담긴 텍스트를 추출할 수 있다는 것을 기억하세요.

In [ ]:
pd.read_xml(StringIO(x2_str))

       name author  year
0   혼공데이터분석    박해선  2022
1  혼공머신+딥러닝    박해선  2020

# 파이썬으로 API 호출하기